# Generated by Django 5.1 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('online_chat', '在线客服'), ('email', '邮件支持'), ('phone', '电话客服'), ('wechat', '微信客服')], max_length=20, unique=True, verbose_name='联系方式类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('contact_info', models.CharField(help_text='如：电话号码、邮箱地址、微信号等', max_length=200, verbose_name='联系信息')),
                ('icon', models.CharField(default='MessageCircle', help_text='Lucide图标名称', max_length=50, verbose_name='图标名称')),
                ('button_text', models.CharField(max_length=50, verbose_name='按钮文字')),
                ('button_link', models.CharField(blank=True, help_text='留空则不可点击', max_length=500, verbose_name='按钮链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '联系方式',
                'verbose_name_plural': '联系方式',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='客服中心', max_length=100, verbose_name='页面标题')),
                ('page_description', models.TextField(blank=True, verbose_name='页面描述')),
                ('show_contact_methods', models.BooleanField(default=True, verbose_name='显示联系方式')),
                ('show_faq', models.BooleanField(default=True, verbose_name='显示常见问题')),
                ('faq_title', models.CharField(default='常见问题', max_length=100, verbose_name='常见问题标题')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客服页面配置',
                'verbose_name_plural': '客服页面配置',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='回答')),
                ('category', models.CharField(default='general', help_text='如：充值问题、支付问题、账号问题等', max_length=50, verbose_name='分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '常见问题',
                'verbose_name_plural': '常见问题',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
