# Generated by Django 5.1.5 on 2026-02-20 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_contactmethod_custom_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default AI Agent', max_length=100, verbose_name='配置名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('ai_display_name', models.CharField(default='AI客服', max_length=100, verbose_name='AI客服显示名称')),
                ('welcome_message', models.TextField(default='您好，欢迎来到客服中心。我是 AI 客服，可以先帮您快速处理问题。', verbose_name='欢迎语')),
                ('fallback_message', models.TextField(default='我已经收到您的问题，正在为您整理答案。若需要人工客服，请发送“转人工”。', verbose_name='兜底回复')),
                ('transfer_keywords', models.TextField(default='转人工,人工客服,真人客服,人工,客服', help_text='用逗号分隔，命中后自动转人工', verbose_name='转人工关键词')),
                ('auto_reply_enabled', models.BooleanField(default=True, verbose_name='是否启用 AI 自动回复')),
                ('show_knowledge_panel', models.BooleanField(default=True, verbose_name='是否展示知识索引')),
                ('max_context_messages', models.PositiveIntegerField(default=6, verbose_name='AI上下文消息条数')),
                ('enable_external_ai', models.BooleanField(default=False, verbose_name='启用外部AI接口')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='外部AI接口地址')),
                ('api_model', models.CharField(blank=True, max_length=120, verbose_name='外部AI模型')),
                ('api_token', models.CharField(blank=True, max_length=255, verbose_name='外部AI Token')),
                ('api_extra_headers', models.JSONField(blank=True, default=dict, verbose_name='额外请求头')),
                ('request_timeout', models.PositiveIntegerField(default=15, verbose_name='请求超时(秒)')),
                ('system_prompt', models.TextField(blank=True, default='你是一个游戏充值网站客服助手，请先基于 FAQ 和站点内容回答，必要时引导转人工。', verbose_name='系统提示词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI客服配置',
                'verbose_name_plural': 'AI客服配置',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='icon',
            field=models.CharField(default='MessageCircle', help_text='Lucide 图标名称', max_length=50, verbose_name='图标名称'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='会话ID')),
                ('visitor_token', models.CharField(db_index=True, max_length=100, verbose_name='访客标识')),
                ('visitor_name', models.CharField(blank=True, max_length=100, verbose_name='访客昵称')),
                ('visitor_contact', models.CharField(blank=True, max_length=120, verbose_name='访客联系方式')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='来源页面')),
                ('status', models.CharField(choices=[('ai', 'AI接待'), ('human', '人工接待'), ('closed', '已关闭')], default='ai', max_length=10, verbose_name='会话状态')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('last_user_message_at', models.DateTimeField(blank=True, null=True, verbose_name='用户最后发言时间')),
                ('last_agent_message_at', models.DateTimeField(blank=True, null=True, verbose_name='客服最后发言时间')),
                ('is_user_waiting', models.BooleanField(default=False, verbose_name='是否待人工回复')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_service_sessions', to=settings.AUTH_USER_MODEL, verbose_name='接待客服')),
            ],
            options={
                'verbose_name': '在线客服会话',
                'verbose_name_plural': '在线客服会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', '用户'), ('ai', 'AI客服'), ('agent', '人工客服'), ('system', '系统消息')], max_length=10, verbose_name='发送者类型')),
                ('sender_name', models.CharField(blank=True, max_length=100, verbose_name='发送者名称')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('is_read_by_agent', models.BooleanField(default=False, verbose_name='人工客服是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_service.chatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '在线客服消息',
                'verbose_name_plural': '在线客服消息',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status', '-updated_at'], name='customer_se_status_0a3183_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['visitor_token', '-created_at'], name='customer_se_visitor_fdcb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'id'], name='customer_se_session_db24da_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'is_read_by_agent'], name='customer_se_session_d9459a_idx'),
        ),
    ]
