# Generated by Django 6.0.1 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_service", "0003_chatagentconfig_alter_contactmethod_icon_chatsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmethod",
            name="button_text_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="按钮文字多语言"),
        ),
        migrations.AddField(
            model_name="contactmethod",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="描述多语言"),
        ),
        migrations.AddField(
            model_name="contactmethod",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="标题多语言"),
        ),
        migrations.AddField(
            model_name="customerserviceconfig",
            name="faq_title_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="常见问题标题多语言"),
        ),
        migrations.AddField(
            model_name="customerserviceconfig",
            name="page_description_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="页面描述多语言"),
        ),
        migrations.AddField(
            model_name="customerserviceconfig",
            name="page_title_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="页面标题多语言"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="回答多语言"),
        ),
        migrations.AddField(
            model_name="faq",
            name="category_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="分类多语言"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="问题多语言"),
        ),
    ]
