# Generated by Django 5.1.5 on 2026-02-21 01:12

import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_content_visibility',
            field=models.CharField(choices=[('private', '仅自己可见'), ('members', '登录用户可见'), ('public', '公开')], default='private', max_length=20, verbose_name='AI内容可见范围'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_isolation_mode',
            field=models.CharField(choices=[('strict', '严格隔离'), ('balanced', '平衡模式')], default='strict', max_length=20, verbose_name='AI隔离策略'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='头像更新时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='显示名称'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sandbox_enabled',
            field=models.BooleanField(default=True, verbose_name='启用用户沙箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sandbox_namespace',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='用户沙箱命名空间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_upload_to, verbose_name='头像'),
        ),
    ]
