# Generated by Django 5.1.5 on 2026-02-22 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_ai_content_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='global_ai_visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Followers'), (2, 'Public')], db_index=True, default=2, verbose_name='全局 AI 可见范围'),
        ),
        migrations.CreateModel(
            name='DirectMessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_dm_threads', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_dm_threads', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '私信会话',
                'verbose_name_plural': '私信会话',
                'db_table': 'direct_message_thread',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('initiator', models.F('recipient')), _negated=True), name='dm_thread_no_self_chat')],
                'unique_together': {('initiator', 'recipient')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
                'db_table': 'user_follow',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='user_follow_no_self_follow')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
