# Generated by Django 6.0.1 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_name_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="作者名称多语言"),
        ),
        migrations.AddField(
            model_name="article",
            name="content_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="文章内容多语言"),
        ),
        migrations.AddField(
            model_name="article",
            name="excerpt_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="摘要多语言"),
        ),
        migrations.AddField(
            model_name="article",
            name="read_time_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="阅读时间多语言"),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="摘要补充多语言"),
        ),
        migrations.AddField(
            model_name="article",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="文章标题多语言"),
        ),
        migrations.AddField(
            model_name="articlecategory",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="分类描述多语言"),
        ),
        migrations.AddField(
            model_name="articlecategory",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="分类名称多语言"),
        ),
        migrations.AddField(
            model_name="articletag",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="标签名称多语言"),
        ),
    ]
