# Generated by Django 5.1.5 on 2026-02-14 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='分类别名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '游戏分类',
                'verbose_name_plural': '游戏分类',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='游戏名称')),
                ('title_tw', models.CharField(blank=True, max_length=200, verbose_name='游戏名称(繁体)')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL别名')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='games/icons/', verbose_name='游戏图标')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='games/banners/', verbose_name='Banner大图')),
                ('developer', models.CharField(blank=True, max_length=100, verbose_name='开发商')),
                ('platform', models.CharField(default='Android / iOS', max_length=100, verbose_name='支持平台')),
                ('regions', models.CharField(blank=True, default='港台服', max_length=200, verbose_name='支持区服')),
                ('server_name', models.CharField(blank=True, max_length=100, verbose_name='服务器')),
                ('description', models.TextField(blank=True, verbose_name='简短介绍')),
                ('description_tw', models.TextField(blank=True, verbose_name='简短介绍(繁体)')),
                ('content', models.TextField(blank=True, verbose_name='游戏详情')),
                ('content_tw', models.TextField(blank=True, verbose_name='游戏详情(繁体)')),
                ('topup_info', models.TextField(blank=True, verbose_name='充值说明')),
                ('topup_info_tw', models.TextField(blank=True, verbose_name='充值说明(繁体)')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO标题')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO描述')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, verbose_name='SEO关键词')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门推荐')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='店长推荐')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='game_page.gamepagecategory', verbose_name='游戏分类')),
            ],
            options={
                'verbose_name': '游戏页面',
                'verbose_name_plural': '游戏页面管理',
                'ordering': ['sort_order', '-published_at', '-created_at'],
            },
        ),
    ]
