# Generated by Django 5.1.5 on 2026-02-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepage',
            name='google_play_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Google Play ID'),
        ),
    ]
