# Generated by Django 5.1.5 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_page", "0002_gamepage_google_play_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepage",
            name="icon_external_url",
            field=models.URLField(blank=True, verbose_name="图标外链URL"),
        ),
    ]
