# Generated by Django 5.1.5 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_page", "0003_gamepage_icon_external_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="default", max_length=50, unique=True, verbose_name="模板键")),
                ("topup_info", models.TextField(blank=True, verbose_name="默认充值说明")),
                ("topup_info_tw", models.TextField(blank=True, verbose_name="默认充值说明(繁体)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "游戏页面模板",
                "verbose_name_plural": "游戏页面模板",
            },
        ),
    ]
