# Generated by Codex on 2026-02-16

import uuid

from django.db import migrations
from django.utils.text import slugify


def fix_empty_category_slug(apps, schema_editor):
    GamePageCategory = apps.get_model('game_page', 'GamePageCategory')

    empty_slug_qs = GamePageCategory.objects.filter(slug='')
    for category in empty_slug_qs:
        base_slug = slugify(category.name) or f'category-{uuid.uuid4().hex[:8]}'
        slug_candidate = base_slug
        suffix = 1
        while GamePageCategory.objects.filter(slug=slug_candidate).exclude(pk=category.pk).exists():
            slug_candidate = f'{base_slug}-{suffix}'
            suffix += 1

        category.slug = slug_candidate
        category.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('game_page', '0004_gamepagetemplate'),
    ]

    operations = [
        migrations.RunPython(fix_empty_category_slug, migrations.RunPython.noop),
    ]
