# Generated by Django 6.0.1 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_page", "0005_fix_empty_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepage",
            name="content_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="游戏详情多语言"),
        ),
        migrations.AddField(
            model_name="gamepage",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="简短介绍多语言"),
        ),
        migrations.AddField(
            model_name="gamepage",
            name="platform_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="支持平台多语言"),
        ),
        migrations.AddField(
            model_name="gamepage",
            name="regions_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="支持区服多语言"),
        ),
        migrations.AddField(
            model_name="gamepage",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="游戏名称多语言"),
        ),
        migrations.AddField(
            model_name="gamepage",
            name="topup_info_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="充值说明多语言"),
        ),
        migrations.AddField(
            model_name="gamepagecategory",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="分类描述多语言"),
        ),
        migrations.AddField(
            model_name="gamepagecategory",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="分类名称多语言"),
        ),
    ]
