# Generated by Django 5.1.5 on 2026-03-20 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_page', '0006_gamepage_i18n_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamepage',
            index=models.Index(fields=['sort_order', 'published_at', 'created_at'], name='gp_sort_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepage',
            index=models.Index(fields=['status', 'published_at'], name='gp_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepage',
            index=models.Index(fields=['category', 'sort_order'], name='gp_category_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepage',
            index=models.Index(fields=['is_hot', 'view_count'], name='gp_hot_view_idx'),
        ),
    ]
