# Generated by Django 5.1.5 on 2026-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='轮播图标题')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='轮播图描述')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='徽章文字')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='轮播图片')),
                ('primary_button_text', models.CharField(default='立即充值', max_length=50, verbose_name='主按钮文字')),
                ('primary_button_link', models.CharField(default='/recharge', max_length=500, verbose_name='主按钮链接')),
                ('secondary_button_text', models.CharField(default='查看详情', max_length=50, verbose_name='次按钮文字')),
                ('secondary_button_link', models.CharField(default='/games', max_length=500, verbose_name='次按钮链接')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认轮播图')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图管理',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
