# Generated by Django 5.1.5 on 2026-01-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hero_carousel', '轮播图区域'), ('features', '核心特性'), ('hot_games', '热门游戏'), ('categories', '游戏分类'), ('latest_news', '最新资讯')], max_length=50, unique=True, verbose_name='板块标识')),
                ('section_name', models.CharField(help_text='例如：轮播图区域、热门游戏等', max_length=100, verbose_name='板块名称')),
                ('is_enabled', models.BooleanField(default=True, help_text='禁用后该板块将不在首页显示', verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前，相同时按创建时间排序', verbose_name='排序')),
                ('config', models.JSONField(blank=True, default=dict, help_text='额外配置参数，例如显示数量、样式等', verbose_name='板块配置')),
                ('view_count', models.IntegerField(default=0, help_text='记录该板块的查看次数', verbose_name='查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页布局',
                'verbose_name_plural': '首页布局管理',
                'db_table': 'layout',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
