# Generated by Django 5.1.5 on 2026-01-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homelayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelayout',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='板块配置参数，包括标题、描述、图片等内容。例如：{"title": "标题", "description": "描述", "icon": "图标"}', verbose_name='板块配置'),
        ),
        migrations.AlterField(
            model_name='homelayout',
            name='section_key',
            field=models.CharField(choices=[('banner_section', '轮播图板块'), ('features', '核心特性板块'), ('hot_games', '热门游戏板块'), ('categories', '游戏分类板块'), ('latest_news', '最新资讯板块')], max_length=50, unique=True, verbose_name='板块标识'),
        ),
        migrations.AlterField(
            model_name='homelayout',
            name='section_name',
            field=models.CharField(help_text='例如：轮播图板块、热门游戏板块等', max_length=100, verbose_name='板块名称'),
        ),
    ]
