# Generated by Django 5.1.5 on 2026-02-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_homelayout_config_alter_homelayout_section_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CYPHER GAME BUY', max_length=100, verbose_name='网站名称')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='网站Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='站点图标')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO关键词')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO描述')),
                ('primary_color', models.CharField(default='#1890ff', max_length=20, verbose_name='主题主色调')),
                ('secondary_color', models.CharField(default='#52c41a', max_length=20, verbose_name='主题辅助色')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='开启后前端将显示维护页面', verbose_name='维护模式')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站全局配置',
                'verbose_name_plural': '网站全局配置',
            },
        ),
    ]
