# Generated by Django 5.1.5 on 2026-02-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='资源文件')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/%Y/%m/', verbose_name='缩略图')),
                ('category', models.CharField(choices=[('background', '背景'), ('icon', '图标'), ('banner', '横幅'), ('ads', '广告位'), ('product', '商品图'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='SEO描述')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(KB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '媒体资源',
                'verbose_name_plural': '媒体资源库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='homelayout',
            name='section_key',
            field=models.CharField(choices=[('banner_section', '首页-轮播图板块'), ('features', '首页-核心特性板块'), ('hot_games', '首页-热门游戏板块'), ('categories', '首页-游戏分类板块'), ('latest_news', '首页-最新资讯板块'), ('articles_page', '资讯列表页头'), ('games_page', '游戏列表页头'), ('customer_service', '客服中心页头'), ('about_page', '关于我们页头'), ('game_detail', '游戏详情页头'), ('login_page', '登录页头')], max_length=50, unique=True, verbose_name='板块标识'),
        ),
    ]
