# Generated by Django 5.1.5 on 2026-02-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mediaasset_alter_homelayout_section_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='主题扩展配置'),
        ),
    ]
