# Generated by hand for media dedup support.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_siteconfig_theme_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Content Hash",
            ),
        ),
    ]
