# Generated by Django 5.1.5 on 2026-02-19 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mediaasset_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=160, unique=True, verbose_name='Owner Key')),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Client ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Draft Title')),
                ('state', models.JSONField(blank=True, default=dict, verbose_name='Draft State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novel_drafts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Novel Draft',
                'verbose_name_plural': 'Novel Drafts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
