# Generated by Django 5.1.5 on 2026-02-19 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_banner_options_alter_homelayout_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=160, verbose_name='Owner Key')),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Client ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Title')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Summary')),
                ('plan', models.JSONField(blank=True, default=dict, verbose_name='Plan')),
                ('chapters', models.JSONField(blank=True, default=list, verbose_name='Chapters')),
                ('cover_image', models.TextField(blank=True, default='', verbose_name='Cover Image')),
                ('character_images', models.JSONField(blank=True, default=list, verbose_name='Character Images')),
                ('chapter_images', models.JSONField(blank=True, default=list, verbose_name='Chapter Images')),
                ('extra_meta', models.JSONField(blank=True, default=dict, verbose_name='Extra Meta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novel_works', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Novel Work',
                'verbose_name_plural': 'Novel Works',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='novelwork',
            index=models.Index(fields=['owner_key', '-updated_at'], name='main_novelw_owner_k_f0e5fb_idx'),
        ),
    ]
