# Generated by Django 5.1.5 on 2026-02-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_novelwork'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlazaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=160, verbose_name='Owner Key')),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Client ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Author Name')),
                ('author_avatar', models.TextField(blank=True, default='', verbose_name='Author Avatar')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('post_type', models.CharField(choices=[('text', 'Text'), ('role_card', 'Role Card'), ('novel_work', 'Novel Work')], default='text', max_length=20, verbose_name='Post Type')),
                ('source_ref', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Ref')),
                ('source_data', models.JSONField(blank=True, default=dict, verbose_name='Source Data')),
                ('like_count', models.IntegerField(default=0, verbose_name='Like Count')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Comment Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaza_posts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Plaza Post',
                'verbose_name_plural': 'Plaza Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlazaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=160, verbose_name='Owner Key')),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.plazapost', verbose_name='Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaza_likes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Plaza Like',
                'verbose_name_plural': 'Plaza Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlazaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=160, verbose_name='Owner Key')),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Client ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Author Name')),
                ('author_avatar', models.TextField(blank=True, default='', verbose_name='Author Avatar')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.plazapost', verbose_name='Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaza_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Plaza Comment',
                'verbose_name_plural': 'Plaza Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='plazapost',
            index=models.Index(fields=['-created_at'], name='plaza_post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='plazapost',
            index=models.Index(fields=['post_type', '-created_at'], name='plaza_post_type_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='plazalike',
            constraint=models.UniqueConstraint(fields=('post', 'owner_key'), name='plaza_like_post_owner_uniq'),
        ),
        migrations.AddIndex(
            model_name='plazacomment',
            index=models.Index(fields=['post', 'created_at'], name='plaza_comment_post_created_idx'),
        ),
    ]
