# Generated by Django 5.1.5 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_plaza_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="badge_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Badge Text I18n"),
        ),
        migrations.AddField(
            model_name="banner",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Banner Description I18n"),
        ),
        migrations.AddField(
            model_name="banner",
            name="primary_button_text_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Primary Button Text I18n"),
        ),
        migrations.AddField(
            model_name="banner",
            name="secondary_button_text_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Secondary Button Text I18n"),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Banner Title I18n"),
        ),
        migrations.AddField(
            model_name="homelayout",
            name="config_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Section Config I18n"),
        ),
        migrations.AddField(
            model_name="homelayout",
            name="section_name_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Section Name I18n"),
        ),
    ]
