# Generated by Django 5.1.5 on 2026-02-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_main_i18n_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="novelwork",
            name="visibility",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Private"), (1, "Followers"), (2, "Public")],
                db_index=True,
                default=2,
                verbose_name="Visibility",
            ),
        ),
        migrations.AddField(
            model_name="plazapost",
            name="visibility",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Private"), (1, "Followers"), (2, "Public")],
                db_index=True,
                default=2,
                verbose_name="Visibility",
            ),
        ),
    ]
