# Generated by Django 5.1.5 on 2026-01-30 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_product', '0003_add_initial_game_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品展示分类',
                'verbose_name_plural': '产品展示分类',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='展示标题')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL别名')),
                ('author_name', models.CharField(default='产品运营', max_length=100, verbose_name='作者名称')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='product_shows/', verbose_name='封面图')),
                ('excerpt', models.TextField(blank=True, default='', max_length=500, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='展示内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_shows', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_shows', to='game_product.game', verbose_name='关联游戏')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_shows', to='game_product_show.productshowcategory', verbose_name='展示分类')),
            ],
            options={
                'verbose_name': '游戏产品展示',
                'verbose_name_plural': '游戏产品展示',
                'ordering': ['-is_top', '-published_at', '-created_at'],
            },
        ),
    ]
