# Generated by Django 5.1.5 on 2026-02-16 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_article', '0001_initial'),
        ('game_page', '0005_fix_empty_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('source_platform', models.CharField(choices=[('bahamut', 'Bahamut'), ('forum', 'Forum'), ('manual', 'Manual')], default='bahamut', max_length=30)),
                ('source_url', models.URLField(blank=True, default='')),
                ('keyword', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('rewriting', 'Rewriting'), ('enriching', 'Enriching'), ('seoing', 'Seoing'), ('publishing', 'Publishing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_crawler_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, null=True, unique=True)),
                ('source_platform', models.CharField(choices=[('bahamut', 'Bahamut'), ('forum', 'Forum'), ('manual', 'Manual')], default='bahamut', max_length=30)),
                ('source_title', models.CharField(blank=True, default='', max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('meta_title', models.CharField(blank=True, default='', max_length=120)),
                ('meta_description', models.CharField(blank=True, default='', max_length=220)),
                ('seo_score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rewrite_model', models.CharField(blank=True, default='', max_length=80)),
                ('rewrite_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_articles', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_articles', to='game_page.gamepage')),
                ('published_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_source_articles', to='game_article.article')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_articles', to='seo_automation.crawlertask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoKeywordWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120)),
                ('keyword_group', models.CharField(blank=True, default='general', max_length=100)),
                ('intent', models.CharField(blank=True, default='informational', max_length=50)),
                ('weight', models.DecimalField(decimal_places=3, default=1.0, max_digits=6)),
                ('language', models.CharField(default='zh-TW', max_length=20)),
                ('locale', models.CharField(default='zh-TW', max_length=20)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-weight', 'keyword'],
                'indexes': [models.Index(fields=['is_active'], name='seo_automat_is_acti_9c56c0_idx'), models.Index(fields=['keyword_group'], name='seo_automat_keyword_21e3e3_idx'), models.Index(fields=['weight'], name='seo_automat_weight_93f05e_idx')],
                'unique_together': {('keyword', 'language', 'locale')},
            },
        ),
        migrations.AddIndex(
            model_name='crawlertask',
            index=models.Index(fields=['status'], name='seo_automat_status_9c19f0_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlertask',
            index=models.Index(fields=['keyword'], name='seo_automat_keyword_5119b2_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlertask',
            index=models.Index(fields=['created_at'], name='seo_automat_created_b91ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='seoarticle',
            index=models.Index(fields=['status'], name='seo_automat_status_ee03fe_idx'),
        ),
        migrations.AddIndex(
            model_name='seoarticle',
            index=models.Index(fields=['game'], name='seo_automat_game_id_e66f16_idx'),
        ),
        migrations.AddIndex(
            model_name='seoarticle',
            index=models.Index(fields=['created_at'], name='seo_automat_created_0bbeb2_idx'),
        ),
    ]
