# Generated by Django 5.1.5 on 2026-02-17 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMApiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(default='grok-4-fast', max_length=120)),
                ('timeout_seconds', models.PositiveIntegerField(default=45)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_llm_api_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
    ]
