"""
Django settings for game_recharge project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-o7m!z2&)d3p%9*-g$w8v7v2r*zb^od@4*rr_b5jys()37-wks8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'simpleui',  # Simple UI 必须放在 django.contrib.admin 之前
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',  # Token 认证
    'corsheaders',
    'django_filters',
    'djoser',  # Djoser 用户认证
    # Local apps
    'main',
    'users',
    'games',
    'orders',
    'payments',
    'game_article',
    # 'game_product',  # Removed
    'customer_service',  # 客服管理
    'footer',  # 页面底部管理
    # 'game_product_show',  # Removed
    'game_page',  # 游戏页面管理
    'seo_automation',  # SEO automation workflow
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'
ROOT_URLCONF = 'game_recharge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 添加模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'game_recharge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='game_recharge'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default='123456'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# 修复数据库日期时间问题：关闭时区支持
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS 开发环境不需要，使用 DEBUG=True 时，Django 会自动从各个 app 的 static 目录加载
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'static_overrides',
]

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Token 认证
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# CORS settings - 配置跨域请求
# 开发环境允许前端访问
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5176',
    'http://127.0.0.1:5176',
    'http://localhost:5177',
    'http://127.0.0.1:5177',
    'http://localhost:5178',
    'http://127.0.0.1:5178',
]

# 允许携带Cookie和认证信息
CORS_ALLOW_CREDENTIALS = True

# 允许的HTTP方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 允许浏览器缓存预检请求的时间（秒）
CORS_PREFLIGHT_MAX_AGE = 86400

# Simple UI 配置
SIMPLEUI_LOGO = '/static/admin/simpleui-x/img/logo.png'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

# 启用多标签页，避免进入子菜单后缺少返回路径
SIMPLEUI_TABS = True

# 首页配置
SIMPLEUI_HOME_PAGE = '/admin/dashboard/'
SIMPLEUI_HOME_TITLE = '运营看板'
SIMPLEUI_HOME_ICON = 'fas fa-tachometer-alt'

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'dynamic': False,
    'tabs': True,
    'menu_display': ['可视化装修', '首页管理', '游戏页面管理', '资讯管理', '客服管理', '页面底部管理', '用户管理'],
    'menus': [
        {
            'name': '可视化装修',
            'icon': 'fas fa-magic',
            'url': '/cms-builder/?v=4',
            'eid': 'cms_builder_v4',
        },
        {
            'app': 'main',
            'name': '首页管理',
            'icon': 'fas fa-cog',
            'models': [
                {
                    'name': '全局配置',
                    'icon': 'fas fa-sliders-h',
                    'url': '/admin/main/siteconfig/',
                    'eid': 'site_config_model_unique',
                },
                {
                    'name': '首页布局',
                    'icon': 'fas fa-th-large',
                    'url': '/admin/main/homelayout/',
                    'eid': 'home_layout_model_unique',
                },
                {
                    'name': '轮播图管理',
                    'icon': 'fas fa-images',
                    'url': '/admin/main/banner/',
                    'eid': 'banner_model_unique',
                },
                {
                    'name': '素材库管理',
                    'icon': 'fas fa-photo-video',
                    'url': '/admin/main/mediaasset/',
                    'eid': 'media_asset_unique',
                },
            ],
            'eid': 'main_app_group_unique',
        },
        {
            'app': 'game_page',
            'name': '游戏页面管理',
            'icon': 'fas fa-gamepad',
            'models': [
                {
                    'name': '游戏分类',
                    'icon': 'fas fa-list',
                    'url': '/admin/game_page/gamepagecategory/',
                    'eid': 1027,
                },
                {
                    'name': '游戏页面',
                    'icon': 'fas fa-file-alt',
                    'url': '/admin/game_page/gamepage/',
                    'eid': 1028,
                },
            ],
            '_weight': 1,
            'eid': 1029,
        },
        {
            'app': 'game_article',
            'name': '资讯管理',
            'icon': 'fas fa-newspaper',
            'models': [
                {
                    'name': '文章分类',
                    'icon': 'fas fa-folder',
                    'url': '/admin/game_article/articlecategory/',
                    'eid': 1008,
                },
                {
                    'name': '文章管理',
                    'icon': 'fas fa-file-alt',
                    'url': '/admin/game_article/article/',
                    'eid': 1009,
                },
                {
                    'name': '文章标签',
                    'icon': 'fas fa-tag',
                    'url': '/admin/game_article/articletag/',
                    'eid': 1010,
                },
                {
                    'name': '评论管理',
                    'icon': 'fas fa-comments',
                    'url': '/admin/game_article/comment/',
                    'eid': 1011,
                },
            ],
            '_weight': 3,
            'eid': 1012,
        },
        {
            'app': 'customer_service',
            'name': '客服管理',
            'icon': 'fas fa-headset',
            'models': [
                {
                    'name': '联系方式',
                    'icon': 'fas fa-phone',
                    'url': '/admin/customer_service/contactmethod/',
                    'eid': 1016,
                },
                {
                    'name': '常见问题',
                    'icon': 'fas fa-question-circle',
                    'url': '/admin/customer_service/faq/',
                    'eid': 1017,
                },
                {
                    'name': '页面配置',
                    'icon': 'fas fa-cog',
                    'url': '/admin/customer_service/customerserviceconfig/',
                    'eid': 1018,
                },
            ],
            '_weight': 4,
            'eid': 1019,
        },
        {
            'app': 'footer',
            'name': '页面底部管理',
            'icon': 'fas fa-th',
            'models': [
                {
                    'name': '底部板块',
                    'icon': 'fas fa-columns',
                    'url': '/admin/footer/footersection/',
                    'eid': 1020,
                },
                {
                    'name': '底部链接',
                    'icon': 'fas fa-link',
                    'url': '/admin/footer/footerlink/',
                    'eid': 1021,
                },
                {
                    'name': '底部配置',
                    'icon': 'fas fa-cog',
                    'url': '/admin/footer/footerconfig/',
                    'eid': 1022,
                },
            ],
            '_weight': 5,
            'eid': 1023,
        },
        {
            'app': 'game_page',
            'name': '游戏页面管理',
            'icon': 'fas fa-file-alt',
            'models': [
                {
                    'name': '页面分类',
                    'icon': 'fas fa-folder',
                    'url': '/admin/game_page/gamepagecategory/',
                    'eid': 1027,
                },
                {
                    'name': '游戏页面',
                    'icon': 'fas fa-file-alt',
                    'url': '/admin/game_page/gamepage/',
                    'eid': 1028,
                },
            ],
            '_weight': 5.6,
            'eid': 1029,
        },
        {
            'app': 'auth',
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fas fa-user',
                    'url': '/admin/auth/user/',
                    'eid': 1013,
                },
                {
                    'name': '用户组',
                    'icon': 'fas fa-users-cog',
                    'url': '/admin/auth/group/',
                    'eid': 1014,
                },
            ],
            '_weight': 6,
            'eid': 1015,
        },
    ]
}

# ==============================================
# 邮件配置 - Email Settings
# ==============================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # 使用 SSL
EMAIL_HOST_USER = '842015629@qq.com'  # 发件人邮箱
EMAIL_HOST_PASSWORD = 'siwlfnlqfxrobahj'  # QQ邮箱授权码
DEFAULT_FROM_EMAIL = '842015629@qq.com'  # 默认发件人

# ==============================================
# Djoser 配置 - 用户认证
# ==============================================
DJOSER = {
    # 用户激活
    'SEND_ACTIVATION_EMAIL': True,  # 发送激活邮件
    'ACTIVATION_URL': 'activate/{uid}/{token}',  # 激活链接路径
    
    # 密码重置
    'SEND_CONFIRMATION_EMAIL': False,  # 关闭密码重置确认邮件
    'PASSWORD_RESET_CONFIRM_URL': 'password-reset/{uid}/{token}',
    
    # 邮件类配置（使用自定义邮件类强制使用前端域名）
    'EMAIL': {
        'activation': 'main.email.CustomActivationEmail',
    },
    
    # 序列化器
    'SERIALIZERS': {
        'user_create': 'djoser.serializers.UserCreateSerializer',
        'user': 'djoser.serializers.UserSerializer',
        'current_user': 'djoser.serializers.UserSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
    },
    
    # 权限
    'PERMISSIONS': {
        'user': ['rest_framework.permissions.IsAuthenticated'],
        'user_list': ['rest_framework.permissions.IsAdminUser'],
    },
    
    # Token 过期时间（秒）
    'TOKEN_MODEL': 'rest_framework.authtoken.models.Token',
    
    # 前端域名（重要：必须与前端实际运行端口一致）
    'DOMAIN': 'localhost:5176',
    'SITE_NAME': 'CYPHER GAME BUY',
    
    # 允许的用户名字符
    'USER_CREATE_PASSWORD_RETYPE': True,  # 注册时需要两次输入密码
    'SET_PASSWORD_RETYPE': True,  # 设置密码时需要两次输入
    'PASSWORD_RESET_CONFIRM_RETYPE': True,  # 密码重置确认需要两次输入
    
    # 使用邮箱登录
    'LOGIN_FIELD': 'email',  # 启用邮箱登录
}

# 用户模型配置（如果使用自定义用户模型）
# AUTH_USER_MODEL = 'users.CustomUser'
