# Generated by Django 5.1 on 2026-01-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(default='© 2026 CYPHER GAME BUY. 版权所有', max_length=200, verbose_name='版权信息')),
                ('show_copyright', models.BooleanField(default=True, verbose_name='显示版权信息')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '页面底部配置',
                'verbose_name_plural': '页面底部配置',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', '关于我们'), ('service', '客服服务'), ('payment', '支付方式'), ('social', '关注我们')], max_length=20, unique=True, verbose_name='板块类型')),
                ('title', models.CharField(max_length=100, verbose_name='板块标题')),
                ('description', models.TextField(blank=True, verbose_name='描述内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '页面底部板块',
                'verbose_name_plural': '页面底部板块',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='链接标题')),
                ('url', models.CharField(help_text='可以是相对路径如/articles，或外部链接如https://twitter.com', max_length=500, verbose_name='链接地址')),
                ('icon', models.CharField(blank=True, help_text='图标类名或Emoji', max_length=50, verbose_name='图标')),
                ('is_external', models.BooleanField(default=False, help_text='外部链接会在新窗口打开', verbose_name='是否外部链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='footer.footersection', verbose_name='所属板块')),
            ],
            options={
                'verbose_name': '底部链接',
                'verbose_name_plural': '底部链接',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
