# Generated by Django 5.1.5 on 2026-02-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerconfig',
            name='copyright_text_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='版权信息多语言'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='链接标题多语言'),
        ),
        migrations.AddField(
            model_name='footersection',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='描述内容多语言'),
        ),
        migrations.AddField(
            model_name='footersection',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='板块标题多语言'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='description',
            field=models.TextField(blank=True, help_text='适用于"关于我们"等需要描述的板块', verbose_name='描述内容'),
        ),
    ]
