# Generated by Django 6.0.1 on 2026-01-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='分类图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '游戏分类',
                'verbose_name_plural': '游戏分类',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('code', models.CharField(choices=[('point', '点券/点卡'), ('vip', '会员'), ('item', '道具'), ('gift', '礼包'), ('other', '其他')], max_length=20, unique=True, verbose_name='类型代码')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='游戏名称')),
                ('icon', models.ImageField(upload_to='games/', verbose_name='游戏图标')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='games/covers/', verbose_name='游戏封面')),
                ('description', models.TextField(blank=True, verbose_name='游戏描述')),
                ('developer', models.CharField(blank=True, max_length=200, verbose_name='开发商')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='game_product.gamecategory', verbose_name='游戏分类')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现价')),
                ('discount', models.IntegerField(default=100, verbose_name='折扣（百分比）')),
                ('stock', models.IntegerField(default=9999, verbose_name='库存')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='game_product.game', verbose_name='所属游戏')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='game_product.producttype', verbose_name='商品类型')),
            ],
            options={
                'verbose_name': '充值商品',
                'verbose_name_plural': '充值商品',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
