# Generated by Django 5.1.5 on 2026-01-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.TextField(blank=True, help_text='充值说明，每行一条', verbose_name='充值说明'),
        ),
        migrations.AddField(
            model_name='game',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='游戏英文名称'),
        ),
        migrations.AddField(
            model_name='game',
            name='payment_methods',
            field=models.CharField(default='alipay,wechat', help_text='用逗号分隔', max_length=200, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='game',
            name='processing_time',
            field=models.CharField(default='1-10分钟', max_length=50, verbose_name='到账时间'),
        ),
        migrations.AddField(
            model_name='game',
            name='regions',
            field=models.CharField(blank=True, default='', help_text='用逗号分隔，如：国服,美服,欧服', max_length=500, verbose_name='支持区服'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='用逗号分隔，如：RPG,开放世界,热门', max_length=500, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='code',
            field=models.CharField(choices=[('international', '国际游戏'), ('hongkong-taiwan', '港台游戏'), ('southeast-asia', '东南亚游戏')], default='international', max_length=50, verbose_name='分类代码'),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='分类图标图片'),
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.CharField(default='', help_text='如：60创世结晶、300点券', max_length=100, verbose_name='充值数量'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='icon',
            field=models.CharField(default='🎮', max_length=10, verbose_name='分类图标Emoji'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, help_text='0表示无折扣', verbose_name='折扣（百分比）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
