# Generated by Django

from django.db import migrations


def add_initial_categories(apps, schema_editor):
    """添加初始游戏分类"""
    GameCategory = apps.get_model('game_product', 'GameCategory')
    
    # 创建初始分类
    categories = [
        {
            'name': '国际游戏',
            'code': 'international',
            'icon': '🌍',
            'sort_order': 1,
            'is_active': True
        },
        {
            'name': '港台游戏',
            'code': 'hongkong-taiwan',
            'icon': '🏮',
            'sort_order': 2,
            'is_active': True
        },
        {
            'name': '东南亚游戏',
            'code': 'southeast-asia',
            'icon': '🌴',
            'sort_order': 3,
            'is_active': True
        },
    ]
    
    for category_data in categories:
        GameCategory.objects.get_or_create(
            code=category_data['code'],
            defaults=category_data
        )


def remove_initial_categories(apps, schema_editor):
    """移除初始游戏分类"""
    GameCategory = apps.get_model('game_product', 'GameCategory')
    GameCategory.objects.filter(
        code__in=['international', 'hongkong-taiwan', 'southeast-asia']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game_product', '0002_game_instructions_game_name_en_game_payment_methods_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories, remove_initial_categories),
    ]
