# Generated by Django 5.1.5 on 2026-02-24 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('seo_article_publish', 'SEO文章发布')], db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('executed', '已执行'), ('failed', '执行失败')], db_index=True, default='pending', max_length=16)),
                ('risk_level', models.PositiveSmallIntegerField(default=2)),
                ('reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('client_id', models.CharField(blank=True, default='', max_length=80)),
                ('client_ip', models.CharField(blank=True, default='', max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_approved_approvals', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_executed_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_requested_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作审批单',
                'verbose_name_plural': '操作审批单',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('request_created', '创建申请'), ('approved', '审批通过'), ('rejected', '审批驳回'), ('executed', '执行成功'), ('failed', '执行失败')], db_index=True, max_length=32)),
                ('actor_name', models.CharField(blank=True, default='', max_length=120)),
                ('client_id', models.CharField(blank=True, default='', max_length=80)),
                ('client_ip', models.CharField(blank=True, default='', max_length=64)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ops_gateway.operationapproval')),
            ],
            options={
                'verbose_name': '操作审计日志',
                'verbose_name_plural': '操作审计日志',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='operationapproval',
            index=models.Index(fields=['action', 'status'], name='ops_gateway_action_171183_idx'),
        ),
        migrations.AddIndex(
            model_name='operationapproval',
            index=models.Index(fields=['idempotency_key', 'action'], name='ops_gateway_idempot_28ddb0_idx'),
        ),
        migrations.AddIndex(
            model_name='operationapproval',
            index=models.Index(fields=['requested_at'], name='ops_gateway_request_689538_idx'),
        ),
        migrations.AddIndex(
            model_name='operationauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='ops_gateway_event_t_464d2c_idx'),
        ),
    ]
