# Generated by Codex on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRobotRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_key", models.CharField(db_index=True, default="daily_full_cycle", max_length=64)),
                ("run_date", models.DateField(db_index=True)),
                ("trigger_source", models.CharField(db_index=True, default="scheduler", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("completed", "完成"),
                            ("partial", "部分完成"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "每日机器人运行记录",
                "verbose_name_plural": "每日机器人运行记录",
                "ordering": ["-run_date", "-started_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="dailyrobotrun",
            constraint=models.UniqueConstraint(
                fields=("run_key", "run_date"),
                name="ops_daily_robot_run_key_date_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyrobotrun",
            index=models.Index(fields=["status", "run_date"], name="ops_gateway_status_9d744f_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyrobotrun",
            index=models.Index(fields=["trigger_source", "run_date"], name="ops_gateway_trigger_511886_idx"),
        ),
    ]
