# Generated by Codex on 2026-02-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ops_gateway", "0002_dailyrobotrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRobotConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_key", models.CharField(default="default", max_length=40, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("daily_hour", models.PositiveSmallIntegerField(default=4)),
                ("poll_seconds", models.PositiveIntegerField(default=900)),
                ("max_running_minutes", models.PositiveIntegerField(default=180)),
                ("import_limit", models.PositiveIntegerField(default=30)),
                ("limit_games", models.PositiveIntegerField(default=6)),
                ("posts_min", models.PositiveIntegerField(default=10)),
                ("posts_max", models.PositiveIntegerField(default=20)),
                ("review_threshold", models.PositiveSmallIntegerField(default=78)),
                ("recent_days", models.PositiveSmallIntegerField(default=30)),
                ("publish_now", models.BooleanField(default=True)),
                ("actor_username", models.CharField(blank=True, default="admin_root", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_daily_robot_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "姣忔棩鑷姩浠诲姟閰嶇疆",
                "verbose_name_plural": "姣忔棩鑷姩浠诲姟閰嶇疆",
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
