# Generated by Codex on 2026-02-25

from django.db import migrations, models


def _sync_publish_status_from_publish_now(apps, schema_editor):
    DailyRobotConfig = apps.get_model("ops_gateway", "DailyRobotConfig")
    for row in DailyRobotConfig.objects.all().only("id", "publish_now", "publish_status"):
        desired = "published" if bool(getattr(row, "publish_now", True)) else "draft"
        if str(getattr(row, "publish_status", "") or "") != desired:
            row.publish_status = desired
            row.save(update_fields=["publish_status"])


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("ops_gateway", "0003_dailyrobotconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrobotconfig",
            name="publish_status",
            field=models.CharField(
                choices=[("draft", "草稿"), ("published", "已发布")],
                default="published",
                max_length=12,
            ),
        ),
        migrations.RunPython(_sync_publish_status_from_publish_now, _noop_reverse),
    ]
