# Generated by Django 5.1.5 on 2026-02-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_gateway", "0004_dailyrobotconfig_publish_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrobotconfig",
            name="max_attempts_per_game",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="dailyrobotconfig",
            name="rewrite_limit",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
