# Generated by Django 5.1.5 on 2026-02-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_gateway', '0005_alter_dailyrobotconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahamutBoardRankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('board_title', models.CharField(max_length=255)),
                ('board_url', models.URLField()),
                ('bsn', models.PositiveIntegerField(db_index=True)),
                ('heat_text', models.CharField(blank=True, default='', max_length=80)),
                ('heat_value', models.PositiveIntegerField(default=0)),
                ('activity_value', models.PositiveIntegerField(default=0)),
                ('is_game', models.BooleanField(default=True)),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(default=0)),
                ('is_new_entry', models.BooleanField(default=False)),
                ('is_rank_rising', models.BooleanField(default=False)),
                ('is_high_rank', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('selected_for_daily', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '巴哈排行榜条目',
                'verbose_name_plural': '巴哈排行榜条目',
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BahamutBoardRankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('trigger_source', models.CharField(db_index=True, default='scheduler', max_length=32)),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '完成'), ('partial', '部分完成'), ('failed', '失败')], db_index=True, default='running', max_length=16)),
                ('total_raw_count', models.PositiveIntegerField(default=0)),
                ('game_count', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(blank=True, default='https://forum.gamer.com.tw/')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '巴哈排行榜快照',
                'verbose_name_plural': '巴哈排行榜快照',
                'ordering': ['-snapshot_date', '-started_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailyrobotconfig',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': '每日自动任务配置', 'verbose_name_plural': '每日自动任务配置'},
        ),
        migrations.RenameIndex(
            model_name='dailyrobotrun',
            new_name='ops_gateway_status_bb2c9e_idx',
            old_name='ops_gateway_status_9d744f_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyrobotrun',
            new_name='ops_gateway_trigger_ea1ab9_idx',
            old_name='ops_gateway_trigger_511886_idx',
        ),
        migrations.AddIndex(
            model_name='bahamutboardrankingsnapshot',
            index=models.Index(fields=['status', 'snapshot_date'], name='ops_gateway_status_f42460_idx'),
        ),
        migrations.AddIndex(
            model_name='bahamutboardrankingsnapshot',
            index=models.Index(fields=['trigger_source', 'snapshot_date'], name='ops_gateway_trigger_85fdc8_idx'),
        ),
        migrations.AddField(
            model_name='bahamutboardrankingentry',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ops_gateway.bahamutboardrankingsnapshot'),
        ),
        migrations.AddIndex(
            model_name='bahamutboardrankingentry',
            index=models.Index(fields=['snapshot', 'rank'], name='ops_gateway_snapsho_52f28e_idx'),
        ),
        migrations.AddIndex(
            model_name='bahamutboardrankingentry',
            index=models.Index(fields=['snapshot', 'selected_for_daily'], name='ops_gateway_snapsho_ba9c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='bahamutboardrankingentry',
            index=models.Index(fields=['snapshot', 'is_game'], name='ops_gateway_snapsho_78682a_idx'),
        ),
        migrations.AddIndex(
            model_name='bahamutboardrankingentry',
            index=models.Index(fields=['bsn'], name='ops_gateway_bsn_14794f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bahamutboardrankingentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'bsn'), name='ops_bahamut_rank_entry_snapshot_bsn_uniq'),
        ),
    ]
