# Generated by Django 5.1.5 on 2026-03-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_gateway', '0006_bahamutboardrankingentry_bahamutboardrankingsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationapproval',
            name='action',
            field=models.CharField(choices=[('seo_article_publish', 'SEO Article Publish'), ('daily_robot_run', 'Daily Robot Run'), ('server_task_exec', 'Server Task Exec')], db_index=True, max_length=64),
        ),
    ]
